version: "3.7"

services:
    harvest-personio-copy-times:
        build: .
        image: phiture/harvest-personio-copy-times
        restart: always
        volumes:
            - ${HOST_LOG_DIR}:/var/cron_log
        command: ["cron", "-f"]
